#[[PowerShell]]

== 結論

* シングルクォーテーションを使うな
* ExecutionPolicyは狭く変更しろ

== 説明

=== シングルクォーテーションを使うな

PowerShellに限らないが、ダブルクォーテーションとシングルクォーテーションでは機能が異なる。

ダブルクォーテーションはクォーテーション内部にある変数はその値を出すように解釈するが、シングルクォーテーションでは変数名がそのまま文字列として解釈される。

概してダブルクォーテーションの方が事故が起こりやすい挙動をするので、必要ない場合はシングルクォーテーションを使うような自分規約があったのだが、それが悪い方向に出た。

タスクスケジューラでps1ファイルを実行させる場合、プログラムに `powershell.exe` あるいは `pwsh.exe` を指定し、引数でスクリプトファイルを指定する。

[source, cmd]
----
powershell.exe -File 'C:\Temp\hoge.ps1'
----

例えば上記のようになる。

これは実際には、コマンドプロンプトから実行される形になるため、その文はコマンドプロンプトの構文として解釈される。

そしてコマンドプロンプトではシングルクォーテーションの解釈がPowerShellと異なり、それが原因で意図していない動作をすることになる。

おそらく _C:\Temp\hoge.ps1_ ではなく _'C:\Temp\hoge.ps1'_ というパスだと解釈している。

そのため、存在しないファイルパスを指定していることになり、タスクは失敗する。

解決としては、**ダブルクォーテーションを使う** か **必要ないならクォーテーションを使わない** となる。

==== なんでシングルクォーテーションを採用したかのより詳細

JSONからデータを読み込んでタスクスケジューラを定義する仕組みを作っていて、JSONの値にダブルクォーテーションを使うとエスケープしないと駄目になり、JSONファイル作成時のミスの原因になりそうだな、と思って、明示的にシングルクォーテーションを採用していた。

=== ExecutionPolicyは狭く変更しろ

面倒なので、`Set-ExecutionPolicy` で変えがちだったのだが、本来的にあまり良くない。

PowerShellスクリプトはバッチファイルと違い、標準の動作がスクリプトの実行ではなく、内容の編集(メモ帳で開かれる)ので、事故が起こる可能性はそうそうないが、システム標準のセキュリティ設定を、システムの大きな要件ではないことでわざわざ緩和する必要はないと考える。

そのため、タスクスケジューラでスクリプトを実行させるだけであれば、`powershell.exe` のオプションである `-ExecutionPolicy` でそのスコープだけ変更するのが、システムとしては正しいと言える。

[source, cmd]
----
powershell.exe -ExecutionPolicy Bypass -File "C:\Temp\hoge.ps1"
----

シングルクォーテーションの問題を含めて、基本形としてはこうなる。
