timezone = "Asia/Tokyo"

[ssg]
#base_url = "https://scraps.magicalsound.net/"
base_url = "https://clesteria.nekoweb.org/"
title = "awkwand junkyard"
lang_code = "ja"
description = "Fragments of personal knowledge."
favicon = "https://memos.magicalsound.net/file/users/clesteria/avatar"
color_scheme = "os_setting"
build_search_index = true
sort_key = "committed_date"
paginate_by = 100
