name: Deploy Scraps to Cloudflare Pages

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: knowledge
  PUBLISH_DIR: public

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Scraps
        uses: baptiste0928/cargo-install@v3
        with:
          crate: scraps

      - name: Build Site
        run: scraps build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PROJECT_NAME }}
          directory: ${{ env.PUBLISH_DIR }}
